### ISSUE TITLE
clickhouse on demo, socket is hang up

### ISSUE THREAD

**Issue by Slach** [mlcraft-io/mlcraft#1]
Dear mlcraft.io team, thanks you for your effort guys! Demo looks great
I tried to add `clickhouse` data source on https://app.mlcraft.org/

```
host: github.demo.altinity.cloud
port 8443
use SSL 
user: demo
password: demo
```
when press "test datasource" failed with error
request
```
{"query":"mutation TestDatasourceMutation($input: TestConnectionInput!) {\n  testConnection(input: $input) {\n    message\n    __typename\n  }\n}\n","operationName":"TestDatasourceMutation","variables":{"input":{"dataSourceId":2}}}
```
response
```
{"errors":[{"message":"Unexpected error value: { error: \"socket hang up\" }","locations":[{"line":2,"column":3}],"path":["testConnection"]}],"data":null}
```

but datasource is live
```
curl -vvv "https://demo:demo@github.demo.altinity.cloud:8443/?query=SHOW+TABLES"
```
looks ok

could you help me resolve issue?

**Comment by ifokeev** [comment]
@Slach Hi! Thanks for your issue, will take into it

**Comment by Slach** [comment]
@ifokeev any news about this issue?

**Comment by ifokeev** [comment]
@Slach will fix in 2-3 days, sorry for the delay

**Comment by ifokeev** [comment]
<img width="1196" alt="Screen Shot 2021-07-02 at 00 05 02" src="https://user-images.githubusercontent.com/2017148/124189322-348efd80-dac9-11eb-9fae-761e4513346d.png">

Fixed. Please, check out

**Comment by Slach** [comment]
thanks a lot it works
