### ISSUE TITLE
Kuberenetes implementation

### ISSUE THREAD

**Issue by jskrzypek** [mlcraft-io/mlcraft#22]
Is there any plan to provide a kubernetes deployment for MLCraft? It doesn't seem too big a lift vs. the docker solution and might actually make this project feasible to run in place of Looker. In the current form I could see my way to playing around with this locaclly a bit, but not ever suggesting that my team try to use it.

**Comment by ifokeev** [comment]
HI @jskrzypek,

No, we have no plans to implement kubernetes deployment.
Contributions are welcome, I can help.
