### ISSUE TITLE
Docker Compose up

### ISSUE THREAD

**Issue by simenandre** [mlcraft-io/mlcraft#27]
Hello 👋 

I'm having issues with the quickstart. Seems like `hasura` exits with code 0.

You can recreate it by running `docker-compose up`.

I'm using a Mac M1 btw, don't know if that would be the issue. I'll try again with a ~X86~x64 later today. 👍

**Comment by ifokeev** [comment]
hi @cobraz,
yes, M1 could be the issue. Need to test it
