### ISSUE TITLE
mlcraft athena datasource connection not working

### ISSUE THREAD

**Issue by dhavalaprashanth** [mlcraft-io/mlcraft#29]
When i try to connect to athena by providing all required aws details
It is showing me an error saying 
"Region is missing"... but i provided it....

You can see the snip below

<img width="784" alt="Screenshot 2022-08-29 152913" src="https://user-images.githubusercontent.com/54313094/187176568-25a01c48-9546-4bb6-982d-e7beff381df1.png">

**Comment by ifokeev** [comment]
Hello. It looks like we have a bug in the cubejs-server, I can try to look at this today.
How urgent do you need it?

**Comment by dhavalaprashanth** [comment]
> 
Thank you for the quick reply . Well, probably it would be great if you  give it to me tomorrow.

**Comment by dhavalaprashanth** [comment]
> Hello. It looks like we have a bug in the cubejs-server, I can try to look at this today. How urgent do you need it?

Hello @ifokeev .Is there any update about this issue? .

**Comment by ifokeev** [comment]
@dhavalaprashanth fixed by https://github.com/mlcraft-io/mlcraft/commit/09a123f98d8dd53ad851f89567c45acfdf5219b4

Sorry for such late reply.
Closing the ticket. Please create a new one if needed.
